In [1]:
import numpy as np
import matplotlib.pyplot as plt

plt.style.use("seaborn-v0_8")

# latex settings for matplotlib
from dataclasses import dataclass
import tyro
from adapt_drones.cfgs.config import *

In [2]:
@dataclass
class Args:
    env_id: str = "traj_v3"
    run_name: str = "different-jazz-16"
    seed: int = 20240915
    agent: str = "RMA_DATT"
    scale: bool = True


args = Args()

cfg = Config(
    env_id=args.env_id,
    seed=args.seed,
    eval=True,
    run_name=args.run_name,
    agent=args.agent,
    scale=args.scale,
)
run_folder = "../runs/" + cfg.grp_name + "/" + cfg.run_name + "/"
results_folder = run_folder + "results-icra/"

phase_1_results = np.load(results_folder + "phase_1_results.npy")
RMA_DATT_results = np.load(results_folder + "rma_datt_results.npy")


In [3]:
phase_1_results.shape, RMA_DATT_results.shape

((2, 5, 4, 9), (2, 5, 4, 9))

In [4]:
num_trajs = phase_1_results.shape[0]


In [5]:
for i in range(num_trajs):
    phase_1_traj = phase_1_results[i]
    print(np.mean(phase_1_traj[:,:,2], axis=1))
    idx_sort_phase = np.argsort(np.mean(phase_1_traj[:,:,2], axis=1))

print("help")
phase_1_results[:,:,:,2]

[0.03434196 0.04022144 0.04296609 0.04005431 0.03810129]
[0.0304072  0.03505253 0.03719539 0.03368274 0.03387013]
help


array([[[0.04465301, 0.03537183, 0.02882045, 0.02852257],
        [0.04521064, 0.04064756, 0.03650462, 0.03852295],
        [0.04766529, 0.04337922, 0.03909585, 0.04172401],
        [0.04738229, 0.04098467, 0.03572609, 0.03612419],
        [0.04556997, 0.03899474, 0.03380926, 0.0340312 ]],

       [[0.03546854, 0.03031667, 0.0283613 , 0.02748231],
        [0.03746202, 0.03505669, 0.03359282, 0.03409861],
        [0.0391689 , 0.03731448, 0.03555507, 0.03674312],
        [0.03734008, 0.03393944, 0.03198381, 0.03146763],
        [0.03844681, 0.03400183, 0.03191638, 0.03111551]]])

In [6]:
print(np.mean(phase_1_results[:,:,:,2],axis=2))
print(np.argsort(np.mean(phase_1_results[:,:,:,2],axis=2)))
sorts = np.argsort(np.mean(phase_1_results[:,:,:,2],axis=2))
print(phase_1_results.shape)
print(phase_1_results[:,sorts[0],:,:].shape)
phase_1_results = phase_1_results[:,sorts[0],:,:]    
print(phase_1_results[:,1:-1,:,:].shape)
phase_1_results = phase_1_results[:,1:-1,:,:]
print(np.mean(phase_1_results[:,:,:,2],axis=2))

[[0.03434196 0.04022144 0.04296609 0.04005431 0.03810129]
 [0.0304072  0.03505253 0.03719539 0.03368274 0.03387013]]
[[0 4 3 1 2]
 [0 3 4 1 2]]
(2, 5, 4, 9)
(2, 5, 4, 9)
(2, 3, 4, 9)
[[0.03810129 0.04005431 0.04022144]
 [0.03387013 0.03368274 0.03505253]]


In [7]:
mean_error = np.mean(phase_1_results[:,:,:,2],axis=1)
mean_error.shape

(2, 4)

In [8]:
phase_1_results[:,:,:,0]


array([[[0.05      , 0.08666667, 0.12333333, 0.16      ],
        [0.05      , 0.08666667, 0.12333333, 0.16      ],
        [0.05      , 0.08666667, 0.12333333, 0.16      ]],

       [[0.05      , 0.08666667, 0.12333333, 0.16      ],
        [0.05      , 0.08666667, 0.12333333, 0.16      ],
        [0.05      , 0.08666667, 0.12333333, 0.16      ]]])

In [9]:
phase_1_results[:,:,:,2]

array([[[0.04556997, 0.03899474, 0.03380926, 0.0340312 ],
        [0.04738229, 0.04098467, 0.03572609, 0.03612419],
        [0.04521064, 0.04064756, 0.03650462, 0.03852295]],

       [[0.03844681, 0.03400183, 0.03191638, 0.03111551],
        [0.03734008, 0.03393944, 0.03198381, 0.03146763],
        [0.03746202, 0.03505669, 0.03359282, 0.03409861]]])

In [13]:
np.mean(phase_1_results[:,:,:,2],axis=1)

array([[0.0460543 , 0.04020899, 0.03534666, 0.03622611],
       [0.03774964, 0.03433265, 0.03249767, 0.03222725]])

In [14]:
np.mean(phase_1_results[:,:,:,2],axis=1).reshape(8)

array([0.0460543 , 0.04020899, 0.03534666, 0.03622611, 0.03774964,
       0.03433265, 0.03249767, 0.03222725])

In [11]:
data = np.zeros((8,7))

In [12]:
data[:,2] = np.mean(phase_1_results[:,:,:,2],axis=1)

ValueError: could not broadcast input array from shape (2,4) into shape (8,)