In [1]:
import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass
import tyro
from adapt_drones.cfgs.config import *


In [2]:
@dataclass
class Args:
    env_id: str = "traj_v2_ctbr"
    run_name: str = "zany-elevator-1"
    seed: int = 20240915
    agent: str = "RMA_DATT"
    scale: bool = True


args = Args()

cfg = Config(
    env_id=args.env_id,
    seed=args.seed,
    eval=True,
    run_name=args.run_name,
    agent=args.agent,
    scale=args.scale,
)
run_folder = "../runs/" + cfg.grp_name + "/" + cfg.run_name + "/"
results_folder = run_folder + "results-icra/"

phase_1_results = np.load(results_folder + "phase_1_results.npy")

In [3]:
# sort the results by mean error
print(phase_1_results.shape)
errors = phase_1_results[:, :, 2]
errors

(50, 11, 8)


array([[0.10984679, 0.0631865 , 0.06457852, 0.07516079, 0.07785106,
        0.07536995, 0.07563045, 0.07856943, 0.08754758, 0.09648393,
        0.09714044],
       [0.26882049, 0.14542079, 0.11059711, 0.08440454, 0.06861827,
        0.06718509, 0.07616184, 0.07202554, 0.08021987, 0.07172614,
        0.06979682],
       [0.07700159, 0.0529721 , 0.06634523, 0.07896428, 0.09569195,
        0.10132125, 0.10922614, 0.123221  , 0.11457942, 0.08591917,
        0.05923371],
       [0.1188871 , 0.072572  , 0.06876457, 0.06079519, 0.05814517,
        0.05566688, 0.05034943, 0.04272474, 0.042173  , 0.04604926,
        0.05312565],
       [0.07422558, 0.05612436, 0.05561966, 0.05740511, 0.05430321,
        0.05366083, 0.06777885, 0.0913994 , 0.11368092, 0.13164661,
        0.14261753],
       [0.10026243, 0.07880829, 0.11452547, 0.15276554, 0.17104599,
        0.18101316, 0.17148076, 0.15733955, 0.13625939, 0.12001178,
        0.11524542],
       [0.17134023, 0.13784901, 0.10595315, 0.07641371, 0.

In [4]:
print(errors.shape)
means = np.mean(phase_1_results[:, :, 2], axis=0)
means

(50, 11)


array([0.11807015, 0.07207619, 0.07058114, 0.07171641, 0.07567913,
       0.08010691, 0.08447871, 0.09076708, 0.09583142, 0.100681  ,
       0.1043281 ])

In [5]:
means.shape 

(11,)

In [6]:
print(phase_1_results[0])

[[6.00000000e-02 4.55100000e+03 1.09846791e-01 1.29212859e-01
  5.21884495e-02 3.54539865e-05 2.46911889e-05 4.89501579e-05]
 [7.00000000e-02 4.55100000e+03 6.31865039e-02 7.33694836e-02
  7.94863857e-02 7.58888302e-05 5.10008732e-05 1.01387438e-04]
 [8.00000000e-02 4.55100000e+03 6.45785193e-02 7.09861469e-02
  1.08658125e-01 1.46577214e-04 9.35566802e-05 1.85805361e-04]
 [9.00000000e-02 4.55100000e+03 7.51607856e-02 8.35152755e-02
  1.40673381e-01 2.59796716e-04 1.56786236e-04 3.09911195e-04]
 [1.00000000e-01 4.55100000e+03 7.78510557e-02 8.68022692e-02
  1.76501867e-01 4.29763604e-04 2.46575306e-04 4.84184471e-04]
 [1.10000000e-01 4.55100000e+03 7.53699452e-02 8.35047026e-02
  2.17113297e-01 6.73590054e-04 3.70700270e-04 7.22789864e-04]
 [1.20000000e-01 4.55100000e+03 7.56304510e-02 8.34069582e-02
  2.63477385e-01 1.01224137e-03 5.39260607e-04 1.04449008e-03]
 [1.30000000e-01 4.55100000e+03 7.85694332e-02 8.68709299e-02
  3.16563844e-01 1.47149323e-03 7.65111367e-04 1.47355872e-03]


In [7]:
print(phase_1_results[0, :, 2])

[0.10984679 0.0631865  0.06457852 0.07516079 0.07785106 0.07536995
 0.07563045 0.07856943 0.08754758 0.09648393 0.09714044]


In [8]:
print(phase_1_results[22, :, 2])

[0.08774877 0.0555706  0.0602525  0.05409174 0.05275644 0.05573283
 0.06352135 0.06376286 0.06073766 0.07488485 0.0803407 ]


In [9]:
np.mean(phase_1_results[:, :, 2], axis=1)

array([0.08194231, 0.1013615 , 0.08767962, 0.06084118, 0.08167837,
       0.13625071, 0.08931735, 0.10125419, 0.10610149, 0.08013094,
       0.07760468, 0.08058519, 0.07511993, 0.06236344, 0.11212806,
       0.07588234, 0.08454031, 0.09006756, 0.06355525, 0.13803713,
       0.0946361 , 0.09975955, 0.06449094, 0.07014531, 0.09119874,
       0.10429277, 0.09338004, 0.08476274, 0.08685755, 0.09007626,
       0.11137848, 0.06704933, 0.09298941, 0.09495102, 0.08962753,
       0.0677636 , 0.10576569, 0.09537511, 0.07714771, 0.0965632 ,
       0.11241608, 0.06704177, 0.07023061, 0.07911316, 0.06787226,
       0.06501613, 0.05761885, 0.11226242, 0.08394177, 0.10308997])

In [10]:
# sort the results by mean error
x = np.array([3,2,1])
np.argsort(x)

array([2, 1, 0])

In [11]:
idx_sort_phase_1 = np.argsort(np.mean(phase_1_results[:, :, 2], axis=1))
idx_sort_phase_1

array([46,  3, 13, 18, 22, 45, 41, 31, 35, 44, 23, 42, 12, 15, 38, 10, 43,
        9, 11,  4,  0, 48, 16, 27, 28,  2,  6, 34, 17, 29, 24, 32, 26, 20,
       33, 37, 39, 21,  7,  1, 49, 25, 36,  8, 30, 14, 47, 40,  5, 19])

In [12]:
sorted_phase_1_results = phase_1_results[idx_sort_phase_1]
print(sorted_phase_1_results.shape)
np.mean(sorted_phase_1_results[:,:,2], axis=1)

(50, 11, 8)


array([0.05761885, 0.06084118, 0.06236344, 0.06355525, 0.06449094,
       0.06501613, 0.06704177, 0.06704933, 0.0677636 , 0.06787226,
       0.07014531, 0.07023061, 0.07511993, 0.07588234, 0.07714771,
       0.07760468, 0.07911316, 0.08013094, 0.08058519, 0.08167837,
       0.08194231, 0.08394177, 0.08454031, 0.08476274, 0.08685755,
       0.08767962, 0.08931735, 0.08962753, 0.09006756, 0.09007626,
       0.09119874, 0.09298941, 0.09338004, 0.0946361 , 0.09495102,
       0.09537511, 0.0965632 , 0.09975955, 0.10125419, 0.1013615 ,
       0.10308997, 0.10429277, 0.10576569, 0.10610149, 0.11137848,
       0.11212806, 0.11226242, 0.11241608, 0.13625071, 0.13803713])

In [36]:
tmp = sorted_phase_1_results[0:10,:,2]
tmp, tmp.shape

(array([[0.07384494, 0.05110573, 0.04625473, 0.03742778, 0.04011297,
         0.05186533, 0.05761414, 0.06349725, 0.06641798, 0.07159623,
         0.07407021],
        [0.1188871 , 0.072572  , 0.06876457, 0.06079519, 0.05814517,
         0.05566688, 0.05034943, 0.04272474, 0.042173  , 0.04604926,
         0.05312565],
        [0.06515771, 0.05102792, 0.06121109, 0.06040657, 0.06143507,
         0.07219334, 0.07210756, 0.06721493, 0.05920987, 0.05698211,
         0.05905165],
        [0.08447019, 0.06391785, 0.04476147, 0.05012785, 0.0476498 ,
         0.0491143 , 0.0496597 , 0.0533759 , 0.06095776, 0.08684378,
         0.10822917],
        [0.08774877, 0.0555706 , 0.0602525 , 0.05409174, 0.05275644,
         0.05573283, 0.06352135, 0.06376286, 0.06073766, 0.07488485,
         0.0803407 ],
        [0.14909279, 0.05702818, 0.04519938, 0.05575682, 0.05805177,
         0.05270804, 0.05576457, 0.06074929, 0.05442829, 0.05310413,
         0.0732942 ],
        [0.09420261, 0.04571757, 0.04467

In [33]:
np.mean(tmp, axis=0), np.std(tmp, axis=0).shape

(array([0.09601079, 0.05510491, 0.05308307, 0.05405166, 0.05604265,
        0.06028025, 0.06407432, 0.0642263 , 0.06281566, 0.06790664,
        0.07437776]),
 (11,))

In [34]:
phase_1 = sorted_phase_1_results[0:10]

In [35]:
phase_1[0,:,0].shape

(11,)